import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import {signIn, useSession} from 'next-auth/react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {data} = useSession()
  
  console.log(data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
          <button onClick={()=>{signIn('google')}}>Sign In</button>

    </>
  )
}
