import Head from "next/head";
import Image from "next/image";
import { getSession, signIn, signOut, useSession } from "next-auth/react";
import { useColorMode } from "@chakra-ui/react";
import { NextPage, NextPageContext } from "next";

const Home: NextPage = () => {
  const { data } = useSession();
  const { colorMode, toggleColorMode } = useColorMode();
  const isDark = colorMode === "dark";

  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {data ? (
          <>
            <button
              onClick={() => {
                signOut();
              }}
            >
              Sign Out
            </button>
          </>
        ) : (
          <button
            onClick={() => {
              signIn("google");
            }}
          >
            Sign In
          </button>
        )}
      </main>
    </>
  );
};
export default Home;

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);
  return {
    props: { session },
  };
}
