import { NextPage, NextPageContext } from "next";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import Auth from "../components/auth/AuthComponent";
import Chat from "../components/chat/Chat";
// import "@testing-library/jest-dom";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {session?.user?.username ? (
          <Chat></Chat>
        ) : (
          <Auth session={session}></Auth>
        )}
      </main>
    </>
  );
};
export default Home;

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);
  return {
    props: { session },
  };
}
